workspace: "E:/research/naturesfrontier/optimizer_running/workspace"
country_list: "Suriname,United States of America"
optimization_output_folder: "OptimizationResults"
objectives:
  - "net_econ_value"
  - "biodiversity"
  - "net_ghg_co2e"
optimization_scenarios:
  - "extensification_bmps_irrigated"
  - "extensification_bmps_rainfed"
  - "extensification_current_practices"
  - "extensification_intensified_irrigated"
  - "extensification_intensified_rainfed"
  - "fixedarea_bmps_irrigated"
  - "fixedarea_bmps_rainfed"
  - "fixedarea_intensified_irrigated"
  - "fixedarea_intensified_rainfed"
  - "forestry_expansion"
  - "grazing_expansion"
  - "restoration"
  - "sustainable_current"